version: '3.8'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    cap_add:
      # Silence message: mbind: Operation not permitted
      # https://github.com/docker-library/mysql/issues/422
      # https://github.com/docker-library/mysql/issues/303
      - SYS_NICE
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'America/Toronto'
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    user: "1000:1000"
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -p 3000 -b '0.0.0.0'
    environment:
      TZ: 'America/Toronto'
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
    depends_on:
      - db

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data:
